# Generated by Django 5.2.4 on 2025-07-04 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
