# Generated by Django 5.2.4 on 2025-07-04 15:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0002_userprofile_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
